### ISSUE TITLE
Feature Request Shift Multiplier Config & More Buttons

### ISSUE THREAD

**Issue by Silarious** [M0diis/ShopGUIPlusEditor#1]
- Add the ability to change the "Shift-click" multiplier instead of just the default "2".
- Add or open the ability to insert more buttons, currently there are 3, default 0.1, 1, & 10.

With both of these features you could easily have granular control over prices from 0.01 to 100000 if for example you have 4 buttons and each with shift click multiplier of 10.

**Comment by M0diis** [comment]
https://github.com/M0diis/ShopGUIPlusEditor/commit/649772cbc1be47147ca601b2b1735b71517a7018 Added a `shift-multiplier` config option for every button, so you can change it to your liking.

https://github.com/M0diis/ShopGUIPlusEditor/blob/649772cbc1be47147ca601b2b1735b71517a7018/src/main/resources/config.yml#L27-L38

As for extra buttons - I will see what I can do.

**Comment by Silarious** [comment]
Thank you very much!
